/*
###############################################################
#  Generated by:      Cadence Innovus 15.20-p005_1
#  OS:                Linux x86_64(Host ID hercules)
#  Generated on:      Sat Nov  2 15:59:14 2019
#  Design:            top
#  Command:           saveNetlist top_pnr.v
###############################################################
*/
/////////////////////////////////////////////////////////////
// Created by: Synopsys DC Expert(TM) in wire load mode
// Version   : N-2017.09-SP4
// Date      : Thu Oct 31 12:47:28 2019
/////////////////////////////////////////////////////////////
module top_DW01_add_0 (
	A, 
	B, 
	CI, 
	SUM, 
	CO, 
	p1);
   input [7:0] A;
   input [7:0] B;
   input CI;
   output [7:0] SUM;
   output CO;
   input p1;

   // Internal wires
   wire FE_OCPN33_dout0_3_;
   wire FE_OCPN32_FE_RN_86_0;
   wire FE_RN_265_0;
   wire FE_RN_264_0;
   wire FE_OCPN31_FE_RN_84_0;
   wire FE_RN_263_0;
   wire FE_RN_17;
   wire FE_RN_262_0;
   wire FE_RN_261_0;
   wire FE_RN_260_0;
   wire FE_RN_259_0;
   wire FE_RN_16;
   wire FE_RN_258_0;
   wire FE_RN_257_0;
   wire FE_RN_256_0;
   wire FE_OCPN29_dout0_1_;
   wire FE_OCPN28_FE_RN_46_0;
   wire FE_RN_254_0;
   wire FE_RN_15;
   wire FE_OCPN27_FE_RN_84_0;
   wire FE_RN_253_0;
   wire FE_RN_14;
   wire FE_RN_252_0;
   wire FE_RN_251_0;
   wire FE_RN_250_0;
   wire FE_RN_12;
   wire FE_RN_249_0;
   wire FE_RN_248_0;
   wire FE_RN_247_0;
   wire FE_RN_246_0;
   wire FE_RN_245_0;
   wire FE_RN_244_0;
   wire FE_RN_242_0;
   wire FE_RN_241_0;
   wire FE_RN_11;
   wire FE_RN_239_0;
   wire FE_RN_237_0;
   wire FE_RN_10;
   wire FE_RN_9;
   wire FE_OCPN23_dout0_2_;
   wire FE_RN_235_0;
   wire FE_RN_232_0;
   wire FE_RN_230_0;
   wire FE_RN_229_0;
   wire FE_RN_228_0;
   wire FE_RN_8;
   wire FE_RN_7;
   wire FE_RN_227_0;
   wire FE_RN_6;
   wire FE_RN_226_0;
   wire FE_RN_225_0;
   wire FE_RN_5;
   wire FE_RN_223_0;
   wire FE_RN_4;
   wire FE_RN_222_0;
   wire FE_RN_221_0;
   wire FE_RN_220_0;
   wire FE_RN_219_0;
   wire FE_RN_218_0;
   wire FE_RN_215_0;
   wire FE_RN_213_0;
   wire FE_RN_210_0;
   wire FE_RN_209_0;
   wire FE_RN_207_0;
   wire FE_RN_206_0;
   wire FE_RN_205_0;
   wire FE_RN_203_0;
   wire FE_RN_202_0;
   wire FE_RN_201_0;
   wire FE_OCPN17_dout0_0_;
   wire FE_RN_122_0;
   wire FE_RN_1;
   wire FE_RN_117_0;
   wire FE_RN_112_0;
   wire FE_RN_93_0;
   wire FE_RN_91_0;
   wire FE_OCPN16_n1;
   wire FE_RN_86_0;
   wire FE_RN_85_0;
   wire FE_RN_84_0;
   wire FE_RN_78_0;
   wire FE_RN_77_0;
   wire FE_RN_76_0;
   wire FE_RN_74_0;
   wire FE_RN_73_0;
   wire FE_RN_72_0;
   wire FE_RN_71_0;
   wire FE_RN_68_0;
   wire FE_RN_67_0;
   wire FE_RN_65_0;
   wire FE_RN_64_0;
   wire FE_RN_63_0;
   wire FE_RN_62_0;
   wire FE_RN_61_0;
   wire FE_RN_60_0;
   wire FE_RN_59_0;
   wire FE_RN_58_0;
   wire FE_RN_57_0;
   wire FE_RN_55_0;
   wire FE_RN_54_0;
   wire FE_RN_53_0;
   wire FE_RN_51_0;
   wire FE_RN_50_0;
   wire FE_RN_48_0;
   wire FE_RN_46_0;
   wire FE_RN_45_0;
   wire FE_RN_44_0;
   wire FE_RN_42_0;
   wire FE_RN_40_0;
   wire FE_RN_39_0;
   wire FE_RN_38_0;
   wire FE_RN_36_0;
   wire FE_RN_34_0;
   wire FE_RN_32_0;
   wire FE_RN_30_0;
   wire FE_RN_28_0;
   wire FE_RN_24_0;
   wire FE_RN_23_0;
   wire FE_RN_22_0;
   wire FE_RN_20_0;
   wire FE_RN_19_0;
   wire FE_RN_18_0;
   wire FE_RN_16_0;
   wire FE_RN_14_0;
   wire FE_RN_10_0;
   wire FE_RN_9_0;
   wire FE_RN_8_0;
   wire FE_RN_6_0;
   wire FE_RN_5_0;
   wire FE_RN_4_0;
   wire FE_RN_3_0;
   wire n1;
   wire carry_6;
   wire carry_5;
   wire carry_4;
   wire carry_3;
   wire carry_2;
   wire carry_1;

   INVX2 FE_OCPC33_dout0_3_ (.A(A[3]),
	.Y(FE_OCPN33_dout0_3_));
   NAND3X1 FE_RC_389_0 (.A(FE_RN_15),
	.B(FE_RN_16),
	.C(FE_RN_7),
	.Y(FE_RN_218_0));
   OAI21X1 FE_RC_388_0 (.A(FE_RN_259_0),
	.B(FE_RN_260_0),
	.C(FE_OCPN27_FE_RN_84_0),
	.Y(carry_4));
   BUFX2 FE_OCPC32_FE_RN_86_0 (.A(FE_RN_86_0),
	.Y(FE_OCPN32_FE_RN_86_0));
   INVX1 FE_RC_387_0 (.A(FE_RN_254_0),
	.Y(FE_RN_5));
   INVX2 FE_RC_386_0 (.A(FE_RN_254_0),
	.Y(FE_RN_264_0));
   AND2X2 FE_RC_385_0 (.A(FE_RN_46_0),
	.B(FE_RN_264_0),
	.Y(FE_RN_265_0));
   NAND2X1 FE_RC_384_0 (.A(FE_RN_218_0),
	.B(FE_RN_265_0),
	.Y(FE_RN_239_0));
   NAND2X1 FE_RC_383_0 (.A(FE_RN_17),
	.B(FE_RN_91_0),
	.Y(carry_3));
   AND2X2 FE_RC_382_0 (.A(FE_RN_91_0),
	.B(FE_RN_17),
	.Y(FE_RN_260_0));
   BUFX4 FE_OCPC31_FE_RN_84_0 (.A(FE_RN_84_0),
	.Y(FE_OCPN31_FE_RN_84_0));
   INVX2 FE_RC_381_0 (.A(A[5]),
	.Y(FE_RN_9_0));
   INVX2 FE_RC_380_0 (.A(FE_RN_20_0),
	.Y(FE_RN_263_0));
   NAND2X1 FE_RC_379_0 (.A(FE_RN_263_0),
	.B(A[5]),
	.Y(FE_RN_86_0));
   AOI22X1 FE_RC_378_0 (.A(FE_RN_258_0),
	.B(FE_RN_256_0),
	.C(FE_RN_206_0),
	.D(FE_RN_205_0),
	.Y(FE_RN_112_0));
   NAND2X1 FE_RC_167_0_dup_dup (.A(B[2]),
	.B(A[2]),
	.Y(FE_RN_17));
   INVX2 FE_RC_377_0 (.A(FE_RN_210_0),
	.Y(FE_RN_261_0));
   NAND2X1 FE_RC_376_0 (.A(FE_RN_232_0),
	.B(FE_RN_230_0),
	.Y(FE_RN_262_0));
   NAND3X1 FE_RC_375_0 (.A(FE_RN_209_0),
	.B(FE_RN_261_0),
	.C(FE_RN_262_0),
	.Y(FE_RN_256_0));
   INVX2 FE_RC_374_0 (.A(FE_OCPN28_FE_RN_46_0),
	.Y(FE_RN_259_0));
   NAND2X1 FE_RC_305_0_dup_dup (.A(B[1]),
	.B(A[1]),
	.Y(FE_RN_16));
   INVX2 FE_RC_370_0 (.A(FE_RN_215_0),
	.Y(FE_RN_257_0));
   AOI21X1 FE_RC_369_0 (.A(FE_RN_209_0),
	.B(FE_RN_213_0),
	.C(FE_RN_257_0),
	.Y(FE_RN_258_0));
   AOI21X1 FE_RC_365_0 (.A(FE_RN_55_0),
	.B(FE_RN_241_0),
	.C(FE_RN_207_0),
	.Y(FE_RN_209_0));
   BUFX2 FE_OCPC29_dout0_1_ (.A(A[1]),
	.Y(FE_OCPN29_dout0_1_));
   BUFX2 FE_OCPC28_FE_RN_46_0 (.A(FE_RN_46_0),
	.Y(FE_OCPN28_FE_RN_46_0));
   NOR2X1 FE_RC_363_0 (.A(B[2]),
	.B(A[2]),
	.Y(FE_RN_254_0));
   NAND2X1 FE_RC_167_0_dup (.A(B[2]),
	.B(A[2]),
	.Y(FE_RN_15));
   BUFX2 FE_OCPC27_FE_RN_84_0 (.A(FE_OCPN31_FE_RN_84_0),
	.Y(FE_OCPN27_FE_RN_84_0));
   NAND3X1 FE_RC_362_0 (.A(FE_RN_16),
	.B(FE_OCPN31_FE_RN_84_0),
	.C(FE_RN_253_0),
	.Y(FE_RN_232_0));
   AND2X2 FE_RC_361_0 (.A(FE_RN_17),
	.B(FE_RN_7),
	.Y(FE_RN_253_0));
   OR2X2 FE_RC_45_0_dup1 (.A(A[3]),
	.B(B[3]),
	.Y(FE_RN_14));
   OAI21X1 FE_RC_358_0 (.A(B[1]),
	.B(A[1]),
	.C(n1),
	.Y(FE_RN_249_0));
   INVX1 FE_RC_357_0 (.A(FE_RN_10_0),
	.Y(FE_RN_252_0));
   MUX2X1 FE_RC_356_0 (.A(FE_RN_252_0),
	.B(FE_RN_227_0),
	.S(carry_5),
	.Y(SUM[5]));
   NAND2X1 FE_RC_355_0 (.A(FE_RN_91_0),
	.B(FE_RN_17),
	.Y(FE_RN_251_0));
   NAND2X1 FE_RC_354_0 (.A(FE_OCPN28_FE_RN_46_0),
	.B(FE_RN_251_0),
	.Y(FE_RN_250_0));
   NAND2X1 FE_RC_351_0 (.A(FE_OCPN27_FE_RN_84_0),
	.B(FE_RN_250_0),
	.Y(FE_RN_246_0));
   OAI21X1 FE_RC_292_0_dup (.A(FE_RN_220_0),
	.B(FE_RN_219_0),
	.C(FE_RN_93_0),
	.Y(FE_RN_12));
   NAND2X1 FE_RC_349_0 (.A(FE_RN_63_0),
	.B(FE_RN_249_0),
	.Y(FE_RN_247_0));
   INVX1 FE_RC_348_0 (.A(FE_RN_203_0),
	.Y(FE_RN_248_0));
   MUX2X1 FE_RC_347_0 (.A(FE_RN_248_0),
	.B(FE_RN_53_0),
	.S(carry_6),
	.Y(SUM[6]));
   NAND2X1 FE_RC_345_0 (.A(FE_RN_5),
	.B(FE_RN_247_0),
	.Y(FE_RN_91_0));
   NAND2X1 FE_RC_342_0 (.A(FE_RN_24_0),
	.B(FE_RN_246_0),
	.Y(FE_RN_235_0));
   INVX2 FE_RC_341_0 (.A(FE_RN_242_0),
	.Y(FE_RN_244_0));
   AND2X2 FE_RC_340_0 (.A(FE_RN_55_0),
	.B(FE_RN_18_0),
	.Y(FE_RN_245_0));
   AOI21X1 FE_RC_339_0 (.A(FE_RN_12),
	.B(FE_RN_245_0),
	.C(FE_RN_244_0),
	.Y(FE_RN_205_0));
   NAND2X1 FE_RC_338_0 (.A(FE_RN_55_0),
	.B(FE_RN_241_0),
	.Y(FE_RN_242_0));
   NAND2X1 FE_RC_335_0 (.A(FE_RN_18_0),
	.B(FE_RN_117_0),
	.Y(FE_RN_19_0));
   INVX2 FE_RC_333_0 (.A(FE_RN_86_0),
	.Y(FE_RN_241_0));
   OR2X2 FE_RC_70_0_dup (.A(FE_OCPN29_dout0_1_),
	.B(B[1]),
	.Y(FE_RN_11));
   NAND2X1 FE_RC_329_0 (.A(FE_OCPN31_FE_RN_84_0),
	.B(FE_RN_239_0),
	.Y(FE_RN_85_0));
   INVX2 FE_RC_328_0 (.A(FE_RN_34_0),
	.Y(FE_RN_237_0));
   NAND2X1 FE_RC_327_0 (.A(FE_RN_237_0),
	.B(A[4]),
	.Y(FE_RN_93_0));
   OAI21X1 FE_RC_326_0 (.A(FE_RN_223_0),
	.B(carry_4),
	.C(FE_RN_235_0),
	.Y(SUM[4]));
   OR2X2 FE_RC_29_0_dup (.A(B[4]),
	.B(A[4]),
	.Y(FE_RN_10));
   NAND2X1 FE_RC_305_0_dup (.A(B[1]),
	.B(A[1]),
	.Y(FE_RN_9));
   BUFX2 FE_OCPC23_dout0_2_ (.A(A[2]),
	.Y(FE_OCPN23_dout0_2_));
   NAND2X1 FE_RC_324_0 (.A(n1),
	.B(FE_RN_67_0),
	.Y(FE_RN_68_0));
   NAND3X1 FE_RC_315_0 (.A(FE_RN_15),
	.B(FE_RN_9),
	.C(FE_RN_226_0),
	.Y(FE_RN_6));
   INVX2 FE_RC_313_0 (.A(FE_RN_32_0),
	.Y(FE_RN_228_0));
   NAND2X1 FE_RC_312_0 (.A(FE_RN_14),
	.B(FE_RN_5),
	.Y(FE_RN_229_0));
   AOI21X1 FE_RC_311_0 (.A(FE_RN_229_0),
	.B(FE_OCPN31_FE_RN_84_0),
	.C(FE_RN_228_0),
	.Y(FE_RN_230_0));
   AND2X1 FE_RC_304_0_dup (.A(A[0]),
	.B(B[0]),
	.Y(FE_RN_8));
   OAI21X1 FE_RC_303_0_dup (.A(B[1]),
	.B(A[1]),
	.C(FE_RN_225_0),
	.Y(FE_RN_7));
   NOR2X1 FE_RC_307_0 (.A(FE_RN_14_0),
	.B(FE_RN_16_0),
	.Y(FE_RN_227_0));
   AND2X1 FE_RC_304_0 (.A(A[0]),
	.B(B[0]),
	.Y(FE_RN_225_0));
   OAI21X1 FE_RC_303_0 (.A(B[1]),
	.B(A[1]),
	.C(FE_RN_8),
	.Y(FE_RN_226_0));
   NOR2X1 FE_RC_301_0 (.A(FE_RN_28_0),
	.B(FE_RN_30_0),
	.Y(FE_RN_223_0));
   OR2X2 FE_RC_45_0_dup (.A(A[3]),
	.B(B[3]),
	.Y(FE_RN_4));
   INVX1 FE_RC_298_0 (.A(FE_RN_84_0),
	.Y(FE_RN_221_0));
   AND2X2 FE_RC_297_0 (.A(FE_RN_4),
	.B(FE_RN_78_0),
	.Y(FE_RN_222_0));
   AOI21X1 FE_RC_296_0 (.A(FE_RN_6),
	.B(FE_RN_222_0),
	.C(FE_RN_221_0),
	.Y(FE_RN_219_0));
   INVX2 FE_RC_293_0 (.A(FE_RN_10),
	.Y(FE_RN_220_0));
   OAI21X1 FE_RC_292_0 (.A(FE_RN_220_0),
	.B(FE_RN_219_0),
	.C(FE_RN_93_0),
	.Y(FE_RN_117_0));
   AND2X1 FE_RC_285_0 (.A(FE_RN_6_0),
	.B(FE_RN_54_0),
	.Y(FE_RN_206_0));
   INVX4 FE_RC_284_0 (.A(FE_RN_54_0),
	.Y(FE_RN_207_0));
   INVX8 FE_RC_281_0 (.A(FE_RN_93_0),
	.Y(FE_RN_210_0));
   NAND2X1 FE_RC_278_0 (.A(FE_RN_55_0),
	.B(FE_RN_18_0),
	.Y(FE_RN_213_0));
   INVX8 FE_RC_276_0 (.A(FE_RN_6_0),
	.Y(FE_RN_215_0));
   INVX8 FE_RC_274_0 (.A(FE_RN_51_0),
	.Y(FE_RN_201_0));
   INVX8 FE_RC_273_0 (.A(FE_RN_50_0),
	.Y(FE_RN_202_0));
   NAND2X1 FE_RC_272_0 (.A(FE_RN_201_0),
	.B(FE_RN_202_0),
	.Y(FE_RN_203_0));
   BUFX2 FE_OCPC17_dout0_0_ (.A(A[0]),
	.Y(FE_OCPN17_dout0_0_));
   INVX2 FE_RC_180_0 (.A(FE_RN_48_0),
	.Y(FE_RN_122_0));
   NAND2X1 FE_RC_179_0 (.A(FE_RN_122_0),
	.B(A[3]),
	.Y(FE_RN_84_0));
   NAND2X1 FE_RC_136_0_dup (.A(FE_RN_32_0),
	.B(FE_RN_85_0),
	.Y(FE_RN_1));
   NAND2X1 FE_RC_170_0 (.A(FE_RN_93_0),
	.B(FE_RN_1),
	.Y(carry_5));
   INVX4 FE_RC_150_0 (.A(FE_RN_112_0),
	.Y(SUM[7]));
   NAND2X1 FE_RC_139_0 (.A(FE_OCPN32_FE_RN_86_0),
	.B(FE_RN_19_0),
	.Y(carry_6));
   BUFX2 FE_OCPC16_n1 (.A(n1),
	.Y(FE_OCPN16_n1));
   NAND2X1 FE_RC_101_0 (.A(FE_RN_63_0),
	.B(FE_RN_68_0),
	.Y(carry_2));
   INVX2 FE_RC_98_0 (.A(B[2]),
	.Y(FE_RN_71_0));
   INVX2 FE_RC_97_0 (.A(p1),
	.Y(FE_RN_72_0));
   OAI21X1 FE_RC_96_0 (.A(FE_RN_72_0),
	.B(FE_RN_71_0),
	.C(FE_RN_5),
	.Y(FE_RN_73_0));
   NAND2X1 FE_RC_95_0 (.A(carry_2),
	.B(FE_RN_73_0),
	.Y(FE_RN_74_0));
   INVX2 FE_RC_93_0 (.A(B[2]),
	.Y(FE_RN_76_0));
   AOI22X1 FE_RC_92_0 (.A(FE_OCPN23_dout0_2_),
	.B(FE_RN_76_0),
	.C(FE_RN_72_0),
	.D(B[2]),
	.Y(FE_RN_77_0));
   OAI21X1 FE_RC_91_0 (.A(FE_RN_77_0),
	.B(carry_2),
	.C(FE_RN_74_0),
	.Y(SUM[2]));
   OR2X2 FE_RC_90_0 (.A(A[2]),
	.B(B[2]),
	.Y(FE_RN_78_0));
   INVX2 FE_RC_81_0 (.A(FE_OCPN16_n1),
	.Y(FE_RN_57_0));
   INVX2 FE_RC_80_0 (.A(B[1]),
	.Y(FE_RN_58_0));
   AND2X2 FE_RC_79_0 (.A(FE_OCPN29_dout0_1_),
	.B(FE_RN_58_0),
	.Y(FE_RN_59_0));
   INVX2 FE_RC_78_0 (.A(B[1]),
	.Y(FE_RN_60_0));
   NOR2X1 FE_RC_77_0 (.A(A[1]),
	.B(FE_RN_60_0),
	.Y(FE_RN_61_0));
   OAI21X1 FE_RC_76_0 (.A(FE_RN_61_0),
	.B(FE_RN_59_0),
	.C(FE_RN_57_0),
	.Y(FE_RN_62_0));
   NAND2X1 FE_RC_75_0 (.A(A[1]),
	.B(B[1]),
	.Y(FE_RN_63_0));
   NAND2X1 FE_RC_74_0 (.A(FE_RN_63_0),
	.B(FE_RN_11),
	.Y(FE_RN_64_0));
   NAND2X1 FE_RC_73_0 (.A(FE_OCPN16_n1),
	.B(FE_RN_64_0),
	.Y(FE_RN_65_0));
   NAND2X1 FE_RC_72_0 (.A(FE_RN_62_0),
	.B(FE_RN_65_0),
	.Y(SUM[1]));
   OR2X2 FE_RC_70_0 (.A(FE_OCPN29_dout0_1_),
	.B(B[1]),
	.Y(FE_RN_67_0));
   INVX2 FE_RC_66_0 (.A(FE_RN_55_0),
	.Y(FE_RN_50_0));
   AND2X2 FE_RC_65_0 (.A(A[6]),
	.B(B[6]),
	.Y(FE_RN_51_0));
   XNOR2X1 FE_RC_63_0 (.A(B[6]),
	.B(A[6]),
	.Y(FE_RN_53_0));
   NAND2X1 FE_RC_61_0 (.A(A[6]),
	.B(B[6]),
	.Y(FE_RN_54_0));
   OR2X2 FE_RC_60_0 (.A(B[6]),
	.B(A[6]),
	.Y(FE_RN_55_0));
   INVX2 FE_RC_56_0 (.A(B[3]),
	.Y(FE_RN_36_0));
   OAI21X1 FE_RC_54_0 (.A(FE_OCPN33_dout0_3_),
	.B(FE_RN_36_0),
	.C(FE_OCPN28_FE_RN_46_0),
	.Y(FE_RN_38_0));
   NAND2X1 FE_RC_53_0 (.A(FE_RN_38_0),
	.B(carry_3),
	.Y(FE_RN_39_0));
   INVX2 FE_RC_52_0 (.A(carry_3),
	.Y(FE_RN_40_0));
   NOR2X1 FE_RC_50_0 (.A(FE_OCPN33_dout0_3_),
	.B(B[3]),
	.Y(FE_RN_42_0));
   NOR2X1 FE_RC_48_0 (.A(A[3]),
	.B(FE_RN_36_0),
	.Y(FE_RN_44_0));
   OAI21X1 FE_RC_47_0 (.A(FE_RN_44_0),
	.B(FE_RN_42_0),
	.C(FE_RN_40_0),
	.Y(FE_RN_45_0));
   NAND2X1 FE_RC_46_0 (.A(FE_RN_39_0),
	.B(FE_RN_45_0),
	.Y(SUM[3]));
   OR2X2 FE_RC_45_0 (.A(B[3]),
	.B(A[3]),
	.Y(FE_RN_46_0));
   INVX2 FE_RC_43_0 (.A(B[3]),
	.Y(FE_RN_48_0));
   INVX2 FE_RC_40_0 (.A(B[4]),
	.Y(FE_RN_22_0));
   INVX2 FE_RC_39_0 (.A(A[4]),
	.Y(FE_RN_23_0));
   OAI21X1 FE_RC_38_0 (.A(FE_RN_23_0),
	.B(FE_RN_22_0),
	.C(FE_RN_32_0),
	.Y(FE_RN_24_0));
   NOR2X1 FE_RC_34_0 (.A(FE_RN_23_0),
	.B(B[4]),
	.Y(FE_RN_28_0));
   NOR2X1 FE_RC_32_0 (.A(A[4]),
	.B(FE_RN_22_0),
	.Y(FE_RN_30_0));
   OR2X2 FE_RC_29_0 (.A(B[4]),
	.B(A[4]),
	.Y(FE_RN_32_0));
   INVX2 FE_RC_27_0 (.A(B[4]),
	.Y(FE_RN_34_0));
   INVX2 FE_RC_24_0 (.A(B[5]),
	.Y(FE_RN_8_0));
   OAI21X1 FE_RC_22_0 (.A(FE_RN_9_0),
	.B(FE_RN_8_0),
	.C(FE_RN_18_0),
	.Y(FE_RN_10_0));
   NOR2X1 FE_RC_18_0 (.A(FE_RN_9_0),
	.B(B[5]),
	.Y(FE_RN_14_0));
   NOR2X1 FE_RC_16_0 (.A(A[5]),
	.B(FE_RN_8_0),
	.Y(FE_RN_16_0));
   OR2X2 FE_RC_13_0 (.A(B[5]),
	.B(A[5]),
	.Y(FE_RN_18_0));
   INVX2 FE_RC_11_0 (.A(B[5]),
	.Y(FE_RN_20_0));
   INVX2 FE_RC_5_0 (.A(B[7]),
	.Y(FE_RN_3_0));
   NAND2X1 FE_RC_4_0 (.A(A[7]),
	.B(FE_RN_3_0),
	.Y(FE_RN_4_0));
   INVX2 FE_RC_3_0 (.A(B[7]),
	.Y(FE_RN_5_0));
   OAI21X1 FE_RC_2_0 (.A(A[7]),
	.B(FE_RN_5_0),
	.C(FE_RN_4_0),
	.Y(FE_RN_6_0));
   AND2X2 U1 (.A(B[0]),
	.B(A[0]),
	.Y(n1));
   XOR2X1 U2 (.A(FE_OCPN17_dout0_0_),
	.B(B[0]),
	.Y(SUM[0]));
endmodule

module top (
	clk, 
	csb0, 
	web0, 
	addr0, 
	din0, 
	dout0, 
	other0, 
	other1);
   input clk;
   input csb0;
   input web0;
   input [8:0] addr0;
   input [7:0] din0;
   output [7:0] dout0;
   input other0;
   output [7:0] other1;

   // Internal wires
   wire FE_OCPN36_dout0_0_;
   wire FE_OCPN20_dout0_3_;
   wire FE_OCPN18_dout0_2_;
   wire [7:0] r_other;

   BUFX2 FE_OCPC37_dout0_0_ (.A(FE_OCPN36_dout0_0_),
	.Y(dout0[0]));
   BUFX2 FE_OCPC21_dout0_3_ (.A(FE_OCPN20_dout0_3_),
	.Y(dout0[3]));
   BUFX2 FE_OCPC19_dout0_2_ (.A(FE_OCPN18_dout0_2_),
	.Y(dout0[2]));
   sram_w8_b512_freepdk45 R0 (.din0(din0),
	.dout0({ dout0[7],
		dout0[6],
		dout0[5],
		dout0[4],
		FE_OCPN20_dout0_3_,
		FE_OCPN18_dout0_2_,
		dout0[1],
		FE_OCPN36_dout0_0_ }),
	.addr0(addr0),
	.csb0(csb0),
	.web0(web0),
	.clk0(clk));
   TSV \TSV_GEN[0].TSV0  (.data_in(r_other[0]),
	.data_out(other1[0]));
   TSV \TSV_GEN[1].TSV0  (.data_in(r_other[1]),
	.data_out(other1[1]));
   TSV \TSV_GEN[2].TSV0  (.data_in(r_other[2]),
	.data_out(other1[2]));
   TSV \TSV_GEN[3].TSV0  (.data_in(r_other[3]),
	.data_out(other1[3]));
   TSV \TSV_GEN[4].TSV0  (.data_in(r_other[4]),
	.data_out(other1[4]));
   TSV \TSV_GEN[5].TSV0  (.data_in(r_other[5]),
	.data_out(other1[5]));
   TSV \TSV_GEN[6].TSV0  (.data_in(r_other[6]),
	.data_out(other1[6]));
   TSV \TSV_GEN[7].TSV0  (.data_in(r_other[7]),
	.data_out(other1[7]));
   top_DW01_add_0 add_26 (.A({ dout0[7],
		dout0[6],
		dout0[5],
		dout0[4],
		FE_OCPN20_dout0_3_,
		FE_OCPN18_dout0_2_,
		dout0[1],
		FE_OCPN36_dout0_0_ }),
	.B(din0),
	.CI(1'b0),
	.SUM(r_other),
	.p1(dout0[2]));
endmodule

